Added tokenize_function
kalininalab/SMTB2024 pull request #14
Opened 2024-07-31 18:27 UTC by Viandya

added tokenize_function, removed some comments and uploaded some changes to pretrain.py file.

2024-07-31 18:34 UTC, devium335 commented
Why is it needed to redefine the token as the function to training? The token function also returns the token the same way as defined here.

2024-07-31 18:36 UTC, devium335 requested changes
This seems to add unnecessary code

2024-07-31 19:58 UTC, devium335 requested changes

2024-07-31 19:58 UTC, devium335 commented on pretrain.py
> +)
The tokenizer is defined earlier

2024-07-31 19:58 UTC, devium335 commented on pretrain.py
> +from transformers import PreTrainedTokenizerFast
Unnecessary as this shouldn't be trained in this file

2024-07-31 19:58 UTC, devium335 commented on pretrain.py
> +def tokenize_function(examples):
What is examples?

2024-08-01 07:51 UTC, Viandya commented
oh, apparently I submitted the wrong code to the pull request, sorry, this code is really useless

2024-08-01 09:17 UTC, closed without merging