added datasets and training
kalininalab/SMTB2024 pull request #21
Opened 2024-08-01 16:16 UTC by sdkaraban

2024-08-01 19:23 UTC, devium335 requested changes

2024-08-01 19:23 UTC, devium335 commented on src/data.py
> +def get_protlist(df):
Add typehinting

2024-08-01 19:23 UTC, devium335 commented on src/data.py
> +def embeddings_to_dataset(dataframe, embeddings, layer):
Add typehinting

2024-08-01 19:23 UTC, devium335 commented on src/data.py
> +def load_dataset(path, nlayers):
Add typehinting

2024-08-03 14:24 UTC, Old-Shatterhand approved these changes

2024-08-03 15:22 UTC, merged