global attention pooling added
kalininalab/SMTB2024 pull request #25
Opened 2024-08-03 16:09 UTC by sdkaraban

2024-08-03 19:28 UTC, ilsenatorov requested changes

2024-08-03 19:28 UTC, ilsenatorov commented on src/pooling.py
> +    def __init__(self, input_dim, hidden_dim=None):  # No need for hidden_dim for global pooling
if you don't use hidden_dim, maybe just remove it?

2024-08-04 09:37 UTC, devium335 commented
Why is beartype being disabled?

2024-08-04 09:39 UTC, devium335 requested changes
Please add type hinting and results from testing code

2024-08-04 09:39 UTC, devium335 commented on src/pooling.py
> +    def forward(self, x):
Add type hinting

2024-08-04 09:39 UTC, devium335 commented on src/pooling.py
> +    def forward(x):
Type hinting

2024-08-04 09:39 UTC, devium335 commented on train.py
> +    def collate_fn(batch):
Type hinting

2024-08-04 14:17 UTC, closed without merging